platform:ios, '6.1'

pod 'SVProgressHUD', '~>1.1.2'
#pod 'AFNetworking',  '~>2.4'
#pod 'MagicalRecord', '~>2.2'

#pod 'CrittercismSDK', '~>5.0.7'

#pod 'Facebook-iOS-SDK', '~>3.23.0'

#pod 'ReactiveCocoa', '~>2.4.4'
#pod 'BlocksKit',     '~>2.2.5'

#pod 'Mantle',        '~>1.5.4'
#pod 'JSONKit',       '~>1.4'

#pod 'ShareKit',      '~>4.0.1'

#pod 'FlurrySDK',               '~>5.4.0'
#pod 'GoogleAnalytics-iOS-SDK', '~>3.10'

#pod 'CorePlot',      '~>1.5.1'

#pod 'DDPageControl', '~>0.1'

#pod 'TTTAttributedLabel', '~>1.13.1'

#pod 'SVPullToRefresh',    '~>0.4.1'

#pod 'SFHFKeychainUtils',  '~>0.0.1'

#pod 'SocketRocket'

#pod 'CocoaLumberjack'

#pod 'TestFlight'
#pod 'HockeyKit'

#pod 'Kiwi'

#pod 'NewRelic'


